version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db # This tells your app to connect to the 'db' service
      - DB_PORT=5432 # Default PostgreSQL port
      - DB_NAME=medisync # Database name to use
      - DB_USER=postgres # PostgreSQL username
      - DB_PASSWORD=postgres # PostgreSQL password
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=medisync
    ports:
      - "5432:5432"

volumes:
  postgres_data:
