services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medisync
    ports:
      - "5432:5432"
    command: >
      bash -c "
        docker-entrypoint.sh postgres &
        until pg_isready -U postgres; do sleep 1; done;
        psql -U postgres -c \"CREATE USER postgres WITH SUPERUSER PASSWORD 'postgres';\"
        psql -U postgres -d medisync -f /docker-entrypoint-initdb.d/schema.sql
        wait
      "

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: medisync
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

volumes:
  postgres_data: